function createfigure(X1, YMatrix1, labels)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 12-May-2022 12:32:35

% Create figure
figure1 = figure('NumberTitle','off','Name','Figure','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
    plot1 = plot(X1,YMatrix1,'LineWidth',2);
for i = 1:length(labels)
    set(plot1(i),'DisplayName',labels{i});
end

% Create ylabel
ylabel({'Normalized Magnitude'});

% Create xlabel
xlabel({'Wavelength (nm)'});

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',24);
% Create legend
legend(axes1,'show');

